### ISSUE TITLE
HDT Updated, plugin won't work

### ISSUE THREAD

**Issue by Chillrox** [ko-vasilev/hearthstone-autosquelch#9]
the Hearthstone deck tracker updated and now this error shows, can't run the plugin.

http://i.imgur.com/JXTgKkC.png

**Comment by justinemerson** [comment]
Looks like the time delay he's using in the code is no longer available as an input since they seem to have stripped the deck exporting code out of HDT.
Just need to replace those variables with some other random amount of milliseconds, I think.

**Comment by Chillrox** [comment]
aw :(, I hope he can manage to fix it soon enough :D. It is a good plugin.

**Comment by TemporalOnline** [comment]
Up... Squelching by hand is tedious!

**Comment by Chillrox** [comment]
Yeah, It does not seem tedious but it actually is, at least for me

**Comment by Chillrox** [comment]
I messaged the author on reddit but I think he is not active anymore

**Comment by Chillrox** [comment]
I did a rollback to version 1.2.5 and plugin still works! Just don't update!

**Comment by justinemerson** [comment]
Want to update so I get the deck importing tools :(

I can fork it and make the change if someone wants to compile it? Just need to change 2 lines but I don't have visual studio.

**Comment by Chillrox** [comment]
now we are missing someone with visual studio then

**Comment by Loomies** [comment]
Anyone know how to fix this? Been using this plugin for a year now and can't play HS without it(yes i hate emotes)

**Comment by Chillrox** [comment]
@Loomies the only way I found to fix it is to rollback HDT to 1.2.5

**Comment by Loomies** [comment]
@Chillrox  thanks this works great, guess I will appreciate this until a new expansion comes out, hopefully new cards wont mess with 1.2.5 that much

**Comment by z33154** [comment]
i've forked and uploaded a working dll

**Comment by z33154** [comment]
I'm new to github, so I have not updated the code on the fork. I'm unsure how to apply the changes using the code on my PC or if I'm going to have to manually alter them.

**Comment by justinemerson** [comment]
Thanks z, I've pasted the link here for those to check in the future:
https://github.com/z33154/hearthstone-autosquelch/releases
Spent hours today banging my head against getting something to compile, glad you were on it :)

**Comment by songhuadan88** [comment]
https://github.com/songhuadan88/hearthstone-autosquelch
This is my extended version of this plugin, and it works well now. Firstly, I thought it was troublesome to move my mouse back from the opposite hero every game, so I made a refinement of this plugin. Then, a problem came out, as discussed in the issue, and I fixed the bug in a somewhat stupid way. However, it can continue to work now. Use it if you would like~

**Comment by z33154** [comment]
@songhuadan88 besides removing the authors name and replacing it with your own, you've done nothing to "extend" the autosquelch plugin. You did add one extra line to return the cursor to your hero, the refinement you spoke of. Otherwise you've decreased the functionality of the plugin by completely removing the class reference HueAndBrightness, and its function calls, and replaced it with a boolean, true. I have already updated the plugin for the current release without loss of functionality, perhaps you should use that release, the alternate version will return the cursor to your hero.

**Comment by z33154** [comment]
@songhuadan88 besides removing the authors name and replacing it with your own, you've done nothing to "extend" the autosquelch plugin. You did add one extra line to return the cursor to your hero, the refinement you spoke of. Otherwise you've decreased the functionality of the plugin by completely removing the class reference HueAndBrightness, and its function calls, and replaced it with a boolean, true. 

I have already updated the plugin for the current release without loss of functionality, perhaps you should use that release. The alternate version will return the cursor to your hero. I could link it again but @justinemerson did for me. Have a great day 👍

**Comment by Chillrox** [comment]
Thanks everyone for the comments and fixes!

**Comment by songhuadan88** [comment]
@z33154 I admit you are right. First, my extension is minor, but I have stated it clearly in ReadMe by "a small refinement", and did not claim it as a significant refinement. However, this functionality is very useful to me, and I believe there exist other people desirable for it. Second, about the class "HueAndBrightness", I did not have much time studying how it works, so I just spent little time to make it continue to work. It is a stupid way, and I admit it, but I don't think I should be criticized for this.

**Comment by z33154** [comment]
@songhuadan88 You removed the authors name and replaced it with your own, this was not you work. Making a note in the Readme is does not make you the author. As a programmer, all we have is intellectual property, and all you did was make a two line revision. If you detected any anger in my reply this is the reason. 

I also do not understand why you would refer people to "semi-working" version when I have already published a patched 100% functioning version of the same plugin. There are two [releases ](https://github.com/z33154/hearthstone-autosquelch/releases)of dlls, an exact copy of the original, and the same thing + move mouse back to hero. This is the same "extended refinement" of your release.

People may use whatever they want, I just want them to be aware of the loss of functionality. "squelchBubbleVisible = true;" is not the proper fix.

**Comment by z33154** [comment]
@songhuadan88 I also want to apologize, I perhaps should not be angry for what you have done. It bothered me when I saw you remove his name from his code, but it is still clearly a fork of the original repository. I have not published to Github before and am new to the nature of open source code. 
So, if I offended you, my apologies.

**Comment by Chillrox** [comment]
Hi @z33154 I have a question about your forked plugin, every time I turn on my PC and hearthstone deck tracker opens, I have to enable manually the plugin. Do you have the same issue or is it from my end? Don't know what to do. I am using the alternative plugin, not the regular one.

**Comment by z33154** [comment]
Hi @Chillrox,
I apologize for the slow reply I haven't had time to play in awhile and didn't notice the email right away. 
I do **_not_** have that problem, just checked today it was enabled from boot, I also use alternative.

There are only two additional lines of code in "alternative. First line, find and store position of your hero. Second line, move mouse to stored hero location after squelch. Neither of those two should have any effect on the plugin staying enabled. 
That said, does the regular version stay enabled on logout/shutdown? My thoughts are perhaps HDT has a cache or settings file somewhere and it hasn't yet noticed you replaced the old file with the new one; or it has and the hashes don't match so it disables plugin thinking its been corrupted or modified? 
My honest recommendation is a fresh install of HDT. A fair number of users have found and downloaded the fork, and because no one else has opened an issue, I can only assume no one else is experiencing the problem. Sorry I couldn't be of more help, let me know if the fresh install works out, enjoy your weekend!

**Comment by justinemerson** [comment]
HDT 1.3.6 broke it again, @z33154

**Comment by fallback1337** [comment]
Where can I find the alternative version 1.25 to download?

**Comment by z33154** [comment]
@fallback1337 What do you mean alternative version 1.25? Early in the thread people were using an older version HDT (1.25) to keep the plugin working.. I think you mean the 'alternative' version I spoke of which can be found [here](https://github.com/z33154/hearthstone-autosquelch/releases) all credit to the original author.

**Comment by ko-vasilev** [comment]
I just deployed an updated version of the plugin, check it out: https://github.com/ko-vasilev/hearthstone-autosquelch/releases/latest
